FROM mongodb/atlas:latest

ENV MONGODB_ATLAS_PUBLIC_API_KEY=jislrgse
ENV MONGODB_ATLAS_PRIVATE_API_KEY=c70b2ab4-0094-42d7-a805-74e998e1f1ba
ENV MONGODB_ATLAS_ORG_ID=641a3e0bbda55b4ee69077ff
ENV MONGODB_ATLAS_PROJECT_ID=641a3e0cbda55b4ee6907808

# WORKDIR /usr/src/app
# COPY products.json /usr/src/app/data/

# #COPY entrypoint.sh /docker-entrypoint-initdb.d/
# COPY init.js /docker-entrypoint-initdb.d/
# ENTRYPOINT ["mongosh", "mongodb+srv://cluster0.o3tufac.mongodb.net/", "--apiVersion", "1", "--username", "<username>"]

EXPOSE 27017
